# Generated by Django 4.1.3 on 2023-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Moderate'), (2, 'Advanced')], default=0),
        ),
    ]
